server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    #active: native
    active: git
  cloud:
   config:
    server:
      git:
        uri: https://github.com/DileepGowda0303/config-server.git
        default-label: main
        timeout: 5
        clone-on-start: true
        force-pull: true
         
         